permalink: /:year-:month-:day-:title/
paginate: 15
markdown: kramdown
encoding: utf-8

# 作者信息
author: 
  name: 邱有景
  email: 295978222@qq.com
  link: http://www.vingeart.cn
  weibo: http://www.vingeart.cn
  github: http://github.com/vingeart
  zhihu: https://www.zhihu.com/people/vingeart

# 站点信息
title: VinGe's Life
description: My personal note-blog.
url: http://www.vingeart.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gavatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
ga:
  id: UA-68479766-4
  url: http://www.iamart.vip


# 多说 设置
# duoshuo_shortname: vingeart

# 主题设置，自动激活某个标签
active: 浅谈

# 首页除了最新文章外显示分类
cates: 
  - React
  - 摄影


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - .idea/